# CH01.1. **텐서(Tensor)**

## 00. **작업 환경 설정**

#### 00.0. **사전 변수 설정**

In [1]:
seed_num = 2025

#### 00.1. **라이브러리 호출 및 옵션 설정**

In [2]:
#(1) Import libraries
import numpy as np
import torch

In [3]:
#(2) Set options
np.random.seed(seed=seed_num)
torch.manual_seed(seed=seed_num)
torch.cuda.manual_seed_all(seed=seed_num)

In [4]:
#(3) Define user-defined function
pass

In [5]:
#(4) Define class
pass

<b></b>

## 01. **텐서(Tensor)**

#### 01.1. **정의** : 데이터를 저장하고, 연산을 수행하며, 딥러닝 모델의 가중치를 나타내는 기본적인 다차원 배열(multidimensional array)

#### 01.2. **특징** :
#### $ \hspace{0.15cm} $ ① GPU 가속 : 대규모 데이터 연산을 GPU를 통해 빠르게 처리 가능
#### $ \hspace{0.15cm} $ ② 자동 미분 : 신경망 학습 시 필요한 그래디언트를 자동으로 계산
#### $ \hspace{0.15cm} $ ③ 유연한 데이터 타입 : 다양한 데이터 타입(정수, 부동소수점 등)을 지원

<b></b>

## 02. **텐서 생성**

#### 02.1. **빈(empty) 텐서 생성** : `torch.empty()`

In [6]:
#(1)
tensor_01 = torch.empty(size=(5, 5), dtype=torch.int8)

#(2)
display(tensor_01)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int8)

#### **(`PLUS`)** 비어있음은 메모리에 존재하던 이전의 값들이 그대로 남아 있을 수 있음을 의미함

#### 02.2. **제로(zero) 텐서 생성** : `torch.zeros()`

In [7]:
#(1)
tensor_02 = torch.zeros(size=(5, 5), dtype=torch.int8)

#(2)
display(tensor_02)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int8)

#### 02.3. **일(one) 텐서 생성** : `torch.ones()`

In [8]:
#(1)
tensor_03 = torch.ones(size=(5, 5), dtype=torch.int8)

#(2)
display(tensor_03)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int8)

#### 02.4. **무작위(random) 텐서 생성** : `torch.rand()`

In [9]:
#(1)
tensor_04 = torch.rand(size=(5, 5))

#(2)
tensor_04

tensor([[0.6850, 0.9355, 0.2900, 0.3991, 0.7470],
        [0.0215, 0.0654, 0.7855, 0.3883, 0.6340],
        [0.9447, 0.4773, 0.2861, 0.3887, 0.1099],
        [0.3606, 0.8450, 0.8059, 0.0520, 0.3438],
        [0.5326, 0.5318, 0.0709, 0.8716, 0.6798]])

#### **(`PLUS`)** 정규분포 기반 무작위 텐서는 `torch.randn()` 임

#### **(`PLUS`)** 하드웨어의 명시적 정의는 `device` 파라미터를 사용함

In [10]:
display(torch.rand(size=(5, 5), device='mps'))

tensor([[0.2974, 0.3231, 0.7999, 0.0102, 0.5798],
        [0.1274, 0.0712, 0.9920, 0.4195, 0.2019],
        [0.2672, 0.9561, 0.8711, 0.1637, 0.9076],
        [0.9068, 0.0281, 0.9371, 0.6617, 0.2224],
        [0.4552, 0.0986, 0.3260, 0.4803, 0.2638]], device='mps:0')

<b></b>

## 03. **타 객체에서 텐서 변환**

#### 03.1. **리스트에서 텐서 변환** : `torch.tensor()`

In [11]:
#(1)
list_01 = [1, 2, 3, 4, 5]

#(2) 
tensor_05 = torch.tensor(data=list_01)

#(3)
display(tensor_05)

tensor([1, 2, 3, 4, 5])

#### 03.2. **넘파이 어레이(array)에서 텐서 생성** : `torch.tensor()`

In [12]:
#(1)
array_01 = np.array(object=[2, 4, 6, 8, 10], dtype=np.int8)

#(2) 
tensor_06 = torch.tensor(data=array_01)

#(3)
display(tensor_06)

tensor([ 2,  4,  6,  8, 10], dtype=torch.int8)

<b></b>

## 04. **텐서 확인**

#### 04.1. **텐서 사이즈 확인** : `torch.tensor.size()` or `torch.tensor.shape`

In [13]:
display(tensor_01.size())

torch.Size([5, 5])

In [14]:
display(tensor_01.shape)

torch.Size([5, 5])

#### **(`PLUS`)** 인덱싱을 통해 내부의 값 추출 가능

In [15]:
display(tensor_01.size()[1])

5

#### 04.2. **텐서 타입 확인** : `type()` 

In [16]:
display(type(tensor_01))

torch.Tensor

<b></b>

## 05. **텐서 사이즈 변환**

#### 05.1. **텐서 차원 변환** : `torch.tensor.reshape()`

In [17]:
display(tensor_04.reshape(shape=(1, 25)))

tensor([[0.6850, 0.9355, 0.2900, 0.3991, 0.7470, 0.0215, 0.0654, 0.7855, 0.3883,
         0.6340, 0.9447, 0.4773, 0.2861, 0.3887, 0.1099, 0.3606, 0.8450, 0.8059,
         0.0520, 0.3438, 0.5326, 0.5318, 0.0709, 0.8716, 0.6798]])

<b></b>

## 06. **텐서 인덱싱**

#### 06.1. **인덱싱** : `torch.tensor[n, ... ]`

In [18]:
display(tensor_05[3])

tensor(4)

#### **(`PLUS`)** 스칼라(단일 데이터) 변환 : `torch.tensor.item()`

In [19]:
display(tensor_05[3].item())

4

#### 06.2. **슬라이싱** : `torch.tensor[n:m, ... ]`

In [20]:
display(tensor_05[2:5])

tensor([3, 4, 5])

<b></b>

## 07. **텐서 연산**

#### 07.1. **텐서 간 덧셈** : `+`

In [21]:
display(tensor_05 + tensor_06)

tensor([ 3,  6,  9, 12, 15])

#### 07.2. **텐서 간 뺄셈** : `-`

In [22]:
display(tensor_05 - tensor_06)

tensor([-1, -2, -3, -4, -5])

#### 07.3. **텐서 간 요소 간(element-wise) 곱셈** : `*`

In [23]:
display(tensor_05 * tensor_06)

tensor([ 2,  8, 18, 32, 50])

#### 07.4. **텐서 간 요소 간(element-wise) 나눗셈** : `/`

In [24]:
display(tensor_05 / tensor_06)

tensor([0.5000, 0.5000, 0.5000, 0.5000, 0.5000])

#### **(`PLUS`)** 텐서들이 다른 하드웨어에 정의됐을 경우, 연산이 불가함

In [25]:
#(1)
tensor_06_mps = tensor_06.to(device='mps')

#(2)
tensor_06_mps

tensor([ 2,  4,  6,  8, 10], device='mps:0', dtype=torch.int8)

In [26]:
#(3)
try : 
    display(tensor_05 + tensor_06_mps)
except RuntimeError as error : 
    print(f'>> AN ERROR OCCURRED. ERROR MESSAGE IS "{error}".')

>> AN ERROR OCCURRED. ERROR MESSAGE IS "Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!".
