# CH00.1. **Tensor**

## 00. **작업 환경 설정**

#### 00.0. **사전 변수 설정**

In [1]:
SEED_NUM = 2025

#### 00.1. **라이브러리 호출 및 옵션 설정**

In [2]:
#(1) Import libraries
import os
import random
import numpy as np
import torch

#(2) Set up options
os.environ['PYTHONHASHSEED'] = str(SEED_NUM)
random.seed(a=SEED_NUM)
np.random.seed(seed=SEED_NUM)
torch.use_deterministic_algorithms(mode=True)
torch.manual_seed(seed=SEED_NUM)

#### 00.2. **사용자정의함수 정의**

In [3]:
pass

#### 00.3. **클래스 정의**

In [4]:
pass

<b></b>

## 01. **텐서(Tensor)**

#### 01.1. **정의** : 데이터를 저장하고, 연산을 수행하며, 딥러닝 모델의 가중치를 나타내는 기본적인 다차원 배열

#### 01.2. **특징** :
#### $ \hspace{0.15cm} $ ① 대규모 데이터 연산을 GPU를 통해 빠르게 처리 가능
#### $ \hspace{0.15cm} $ ② 신경망 학습 시 필요한 그래디언트를 자동으로 계산

<b></b>

## 02. **텐서 생성**

#### 02.1. **빈(empty) 텐서 생성** : `torch.empty()`

In [5]:
#(1) Define `tensor_01`
tensor_01 = torch.empty(size=(5, 5), dtype=torch.int8)

#(2) Print `tensor_01`
tensor_01

tensor([[127, 127, 127, 127, 127],
        [127, 127, 127, 127, 127],
        [127, 127, 127, 127, 127],
        [127, 127, 127, 127, 127],
        [127, 127, 127, 127, 127]], dtype=torch.int8)

#### **(`PLUS`)** 비어있음은 메모리에 존재하던 이전의 값들이 그대로 남아 있을 수 있음을 의미함

#### 02.2. **제로(zero) 텐서 생성** : `torch.zeros()`

In [6]:
#(1) Define `tensor_02`
tensor_02 = torch.zeros(size=(5, 5), dtype=torch.int8)

#(2)
tensor_02

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int8)

#### 02.3. **일(one) 텐서 생성** : `torch.ones()`

In [7]:
#(1) Define `tensor_03`
tensor_03 = torch.ones(size=(5, 5), dtype=torch.int8)

#(2)
tensor_03

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int8)

#### 02.4. **무작위(random) 텐서 생성** : `torch.rand()`

In [8]:
#(1) Define `tensor_04`
tensor_04 = torch.rand(size=(5, 5))

#(2)
tensor_04

tensor([[0.6850, 0.9355, 0.2900, 0.3991, 0.7470],
        [0.0215, 0.0654, 0.7855, 0.3883, 0.6340],
        [0.9447, 0.4773, 0.2861, 0.3887, 0.1099],
        [0.3606, 0.8450, 0.8059, 0.0520, 0.3438],
        [0.5326, 0.5318, 0.0709, 0.8716, 0.6798]])

#### **(`PLUS`)** 정규분포 기반 무작위 텐서는 `torch.randn()` 임

#### **(`PLUS`)** 텐서 정의 시 디바이스를 명시적으로 할당하고자 할 경우 `device` 파라미터를 사용함

In [9]:
torch.rand(size=(5, 5), device='mps')

tensor([[0.2974, 0.3231, 0.7999, 0.0102, 0.5798],
        [0.1274, 0.0712, 0.9920, 0.4195, 0.2019],
        [0.2672, 0.9561, 0.8711, 0.1637, 0.9076],
        [0.9068, 0.0281, 0.9371, 0.6617, 0.2224],
        [0.4552, 0.0986, 0.3260, 0.4803, 0.2638]], device='mps:0')

<b></b>

## 03. **타 객체에서 텐서 변환**

#### 03.1. **리스트에서 텐서 변환** : `torch.tensor()`

In [10]:
#(1) Define `list_01`
list_01 = [1, 2, 3, 4, 5]

#(2) Define `tensor_05`
tensor_05 = torch.tensor(data=list_01)

#(3) Print `tensor_05`
tensor_05

tensor([1, 2, 3, 4, 5])

#### 03.2. **넘파이 어레이(array)에서 텐서 생성** : `torch.tensor()`

In [11]:
#(1) Define `array_01`
array_01 = np.array(object=[2, 4, 6, 8, 10], dtype=np.int8)

#(2) Define `tensor_06`
tensor_06 = torch.tensor(data=array_01)

#(3) Print `tensor_06`
tensor_06

tensor([ 2,  4,  6,  8, 10], dtype=torch.int8)

<b></b>

## 04. **텐서 확인**

#### 04.1. **텐서 사이즈 확인** : `torch.Tensor.size()` or `torch.Tensor.shape`

In [12]:
tensor_01.size()

torch.Size([5, 5])

In [13]:
tensor_01.shape

torch.Size([5, 5])

#### **(`PLUS`)** 인덱싱을 통해 내부의 값 추출 가능

In [14]:
tensor_01.size()[1]

5

#### 04.2. **텐서 타입 확인** : `type()` 

In [15]:
type(tensor_01)

torch.Tensor

<b></b>

## 05. **텐서 형태(shape) 변환**

#### 05.1. **텐서 차원 변환** : `torch.Tensor.reshape()`

In [16]:
tensor_04.reshape(shape=(1, 25))

tensor([[0.6850, 0.9355, 0.2900, 0.3991, 0.7470, 0.0215, 0.0654, 0.7855, 0.3883,
         0.6340, 0.9447, 0.4773, 0.2861, 0.3887, 0.1099, 0.3606, 0.8450, 0.8059,
         0.0520, 0.3438, 0.5326, 0.5318, 0.0709, 0.8716, 0.6798]])

#### 05.2. **텐서 차원 순서 변환** : `torch.Tensor.tranpose()`

In [17]:
tensor_04.transpose(dim0=1, dim1=0)

tensor([[0.6850, 0.0215, 0.9447, 0.3606, 0.5326],
        [0.9355, 0.0654, 0.4773, 0.8450, 0.5318],
        [0.2900, 0.7855, 0.2861, 0.8059, 0.0709],
        [0.3991, 0.3883, 0.3887, 0.0520, 0.8716],
        [0.7470, 0.6340, 0.1099, 0.3438, 0.6798]])

#### **(`PLUS`) 명시적 차원 순서 변환** : `torch.Tensor.permute()`

In [18]:
tensor_04.permute(dims=[1, 0])

tensor([[0.6850, 0.0215, 0.9447, 0.3606, 0.5326],
        [0.9355, 0.0654, 0.4773, 0.8450, 0.5318],
        [0.2900, 0.7855, 0.2861, 0.8059, 0.0709],
        [0.3991, 0.3883, 0.3887, 0.0520, 0.8716],
        [0.7470, 0.6340, 0.1099, 0.3438, 0.6798]])

<b></b>

## 06. **텐서 인덱싱**

#### 06.1. **인덱싱** : `torch.Tensor[n, ··· ]`

In [19]:
tensor_05[3]

tensor(4)

#### **(`PLUS`)** 스칼라(단일 데이터) 변환 : `torch.Tensor.item()`

In [20]:
tensor_05[3].item()

4

#### 06.2. **슬라이싱** : `torch.Tensor[n:m, ··· ]`

In [21]:
tensor_05[2:5]

tensor([3, 4, 5])

<b></b>

## 07. **텐서 요소 간(element-wise) 연산**

#### 07.1. **덧셈** : `+`

In [22]:
tensor_05 + tensor_06

tensor([ 3,  6,  9, 12, 15])

#### 07.2. **뺄셈** : `-`

In [23]:
tensor_05 - tensor_06

tensor([-1, -2, -3, -4, -5])

#### 07.3. **곱셈** : `*`

In [24]:
tensor_05 * tensor_06

tensor([ 2,  8, 18, 32, 50])

#### 07.4. **나눗셈** : `/`

In [25]:
tensor_05 / tensor_06

tensor([0.5000, 0.5000, 0.5000, 0.5000, 0.5000])